= StrangeSkies - Modabi

image:http://img.shields.io/travis/StrangeSkies/uk.co.strangeskies.modabi.svg[Travis CI, link="https://travis-ci.org/StrangeSkies/uk.co.strangeskies.modabi"]
image:https://img.shields.io/github/license/StrangeSkies/uk.co.strangeskies.modabi.svg[License, link="https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29"]

Modabi is a Modular Data Binding library for Java, which aims to provide users with the most flexible and comprehensive feature set possible.

Modabi can be used to provide mappings between Java objects in memory and a number of external formats, including Yaml and XML, without any modification to existing business objects.

== Features

* Format agnostic; support for XML, YAML, binary blob, etc.
* Binds to interface, not implementation, perfect for e.g. OSGi environments.
* Type safety is best in class, including type inference.
* Supports complex binding rules, e.g. binding to the builder pattern, so it's easy to bind to existing APIs without modification.
* Simple use cases only require simple schemata, intelligent automatic default matching of data elements to methods.
* Schemata are themselves defined and bound by a provided meta-schema, and so can be designed in any supported format.

== Where to begin

* https://github.com/StrangeSkies/uk.co.strangeskies.modabi/wiki[Wiki]
* https://strangeskies.github.io/uk.co.strangeskies.modabi/[Javadoc]
* https://not-yet[Binaries]
